import { supabase } from '../lib/supabase';
import { STORAGE_CONFIG } from '../config/storage';

export interface FileValidationResult {
  valid: boolean;
  error?: string;
}

export interface UploadResult {
  success: boolean;
  publicUrl?: string;
  filePath?: string;
  fileName?: string;
  fileSize?: number;
  error?: string;
}

/**
 * Checks if Supabase client is properly configured with live credentials
 */
export function isSupabaseConfigured(): boolean {
  const url = import.meta.env.VITE_SUPABASE_URL;
  const key = import.meta.env.VITE_SUPABASE_ANON_KEY;
  return Boolean(url && key && !url.includes('placeholder') && key !== 'placeholder');
}

/**
 * Format bytes into human-readable size string (e.g. "2.4 MB")
 */
export function formatFileSize(bytes?: number): string {
  if (!bytes || bytes === 0) return '0 B';
  const k = 1024;
  const sizes = ['B', 'KB', 'MB', 'GB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return `${parseFloat((bytes / Math.pow(k, i)).toFixed(1))} ${sizes[i]}`;
}

/**
 * Sanitizes a filename to prevent path traversal and invalid characters
 */
export function sanitizeFilename(filename: string): string {
  // Strip path traversal attempts and special characters
  const baseName = filename.replace(/^.*[\\/]/, '');
  const cleanName = baseName.replace(/[^a-zA-Z0-9._-]/g, '_');
  const timestamp = Date.now();
  return `${timestamp}_${cleanName}`;
}

/**
 * Extract filename from a storage URL or path
 */
export function getFilenameFromUrl(url?: string | null): string {
  if (!url) return '';
  try {
    const parts = url.split('/');
    const lastPart = parts[parts.length - 1];
    // Remove query params if any
    const cleanLast = lastPart.split('?')[0];
    // Remove timestamp prefix if generated by us
    return cleanLast.replace(/^\d+_/, '') || cleanLast;
  } catch {
    return 'attachment';
  }
}

/**
 * Validates file type, size, and validity
 */
export function validateAttachmentFile(file: File): FileValidationResult {
  if (!file || file.size === 0) {
    return { valid: false, error: 'Empty or invalid file.' };
  }

  // Check file size
  if (file.size > STORAGE_CONFIG.MAX_FILE_SIZE_BYTES) {
    return {
      valid: false,
      error: `File is too large. Maximum allowed size is ${STORAGE_CONFIG.MAX_FILE_SIZE_MB}MB.`,
    };
  }

  // Check file extension
  const extension = `.${file.name.split('.').pop()?.toLowerCase()}`;
  const isAllowedExt = STORAGE_CONFIG.ALLOWED_EXTENSIONS.includes(extension as any);
  const isAllowedMime = STORAGE_CONFIG.ALLOWED_MIME_TYPES.includes(file.type as any);

  if (!isAllowedExt && !isAllowedMime) {
    return {
      valid: false,
      error: 'Unsupported file type. Allowed formats: PDF, DOC, DOCX, PPT, PPTX, PNG, JPG, JPEG, WEBP.',
    };
  }

  return { valid: true };
}

/**
 * Uploads an academic event attachment to Supabase Storage
 */
export async function uploadEventAttachment(
  file: File,
  eventId: string
): Promise<UploadResult> {
  const validation = validateAttachmentFile(file);
  if (!validation.valid) {
    return {
      success: false,
      error: validation.error || 'Invalid file.',
    };
  }

  const safeFileName = sanitizeFilename(file.name);
  const filePath = `academic-events/${eventId}/${safeFileName}`;

  // If Supabase is not configured (demo/local mode without live backend keys),
  // handle gracefully by creating a local object reference for immediate preview
  if (!isSupabaseConfigured()) {
    const objectUrl = URL.createObjectURL(file);
    return {
      success: true,
      publicUrl: objectUrl,
      filePath,
      fileName: file.name,
      fileSize: file.size,
    };
  }

  try {
    const { data, error } = await supabase.storage
      .from(STORAGE_CONFIG.BUCKET_NAME)
      .upload(filePath, file, {
        cacheControl: '3600',
        upsert: true,
      });

    if (error) {
      console.warn('Supabase storage upload error:', error);
      // If bucket does not exist or user unauthenticated, provide clear error
      return {
        success: false,
        error: error.message || 'Failed to upload attachment to Supabase Storage.',
      };
    }

    // Retrieve public URL
    const { data: publicUrlData } = supabase.storage
      .from(STORAGE_CONFIG.BUCKET_NAME)
      .getPublicUrl(data.path);

    return {
      success: true,
      publicUrl: publicUrlData.publicUrl,
      filePath: data.path,
      fileName: file.name,
      fileSize: file.size,
    };
  } catch (err: unknown) {
    console.error('Storage upload exception:', err);
    return {
      success: false,
      error: err instanceof Error ? err.message : 'Unexpected storage upload error.',
    };
  }
}

/**
 * Deletes an attachment from Supabase Storage given its URL or path
 */
export async function deleteEventAttachment(attachmentUrlOrPath: string): Promise<boolean> {
  if (!attachmentUrlOrPath || !isSupabaseConfigured()) {
    return true;
  }

  try {
    let storagePath = attachmentUrlOrPath;

    // If it's a full public URL, extract the bucket-relative path
    if (attachmentUrlOrPath.includes(STORAGE_CONFIG.BUCKET_NAME)) {
      const match = attachmentUrlOrPath.split(`${STORAGE_CONFIG.BUCKET_NAME}/`)[1];
      if (match) {
        storagePath = decodeURIComponent(match.split('?')[0]);
      }
    }

    // Only delete if it's within the academic-events/ folder to avoid deleting arbitrary files
    if (!storagePath.startsWith('academic-events/')) {
      return false;
    }

    const { error } = await supabase.storage
      .from(STORAGE_CONFIG.BUCKET_NAME)
      .remove([storagePath]);

    if (error) {
      console.warn('Failed to delete storage file:', error);
      return false;
    }

    return true;
  } catch (err) {
    console.warn('Storage deletion error:', err);
    return false;
  }
}
